//// CHANGE name=change0
CREATE MEMORY TABLE TABLE_A(A_ID INTEGER NOT NULL PRIMARY KEY,B_ID INTEGER NOT NULL,STRING_FIELD VARCHAR(30),TIMESTAMP_FIELD TIMESTAMP,C_ID INTEGER,EXTRA1 INTEGER,EXTRA2 INTEGER,EXTRA3 INTEGER)
GO

//// CHANGE name=change1
ALTER TABLE TABLE_A ADD FOREIGN KEY(B_ID) REFERENCES TABLE_B(B_ID)
GO
