/****** Object:  Table [dbo].[TestTableA]    Script Date: 1/1/2017 12:00:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TestTableA](
	[id] [int] NOT NULL,
	[tId] [int] NULL,
	[test] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[fk] [int] NOT NULL,
 CONSTRAINT [TestTableA_PK] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IND1]    Script Date: 1/1/2017 12:00:00 AM ******/
CREATE NONCLUSTERED INDEX [IND1] ON [dbo].[TestTableA]
(
	[test] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TestTableA]  WITH CHECK ADD FOREIGN KEY([fk])
REFERENCES [dbo].[TestTable] ([idField])
GO
