//// CHANGE name=chng1
CREATE TABLE TABLE_C (
	C_ID    BIGINT NOT NULL
)

//// CHANGE name=chng2
ALTER TABLE TABLE_C ADD COLUMN COL2 INT NULL
GO

//// CHANGE name=chng3
ALTER TABLE TABLE_C ADD COLUMN COL3 INT NULL
GO
