CREATE OR REPLACE PACKAGE PKG_REMOVING_ALL
AS
    FUNCTION REMOVING_ALL return integer;
END;

GO

//// BODY
CREATE OR REPLACE PACKAGE BODY PKG_REMOVING_ALL
AS
    FUNCTION PKG_REMOVING_ALL
    RETURN integer IS
    BEGIN
        RETURN 1;
    END;
END;
GO
