--------------------------------------------------------
--  DDL for Table ARTIFACTDEPLOYMENT
--------------------------------------------------------

  CREATE TABLE "DBDEPLOY01"."ARTIFACTDEPLOYMENT"
   (	"ARTFTYPE" VARCHAR2(31 BYTE),
	"ARTIFACTPATH" VARCHAR2(255 BYTE),
	"OBJECTNAME" VARCHAR2(255 BYTE),
	"ACTIVE" NUMBER(*,0),
	"CHANGETYPE" VARCHAR2(255 BYTE),
	"CONTENTHASH" VARCHAR2(255 BYTE),
	"DBSCHEMA" VARCHAR2(255 BYTE),
	"DEPLOY_USER_ID" VARCHAR2(32 BYTE),
	"TIME_INSERTED" TIMESTAMP (6),
	"TIME_UPDATED" TIMESTAMP (6),
	"ROLLBACKCONTENT" VARCHAR2(2048 BYTE),
	"INSERTDEPLOYID" NUMBER(19,0),
	"UPDATEDEPLOYID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARTIFACTEXECUTION
--------------------------------------------------------

  CREATE TABLE "DBDEPLOY01"."ARTIFACTEXECUTION"
   (	"ID" NUMBER(19,0),
	"STATUS" CHAR(1 BYTE),
	"DEPLOYTIME" TIMESTAMP (6),
	"EXECUTORID" VARCHAR2(128 BYTE),
	"TOOLVERSION" VARCHAR2(32 BYTE),
	"INIT_COMMAND" NUMBER(*,0),
	"ROLLBACK_COMMAND" NUMBER(*,0),
	"REQUESTERID" VARCHAR2(128 BYTE),
	"REASON" VARCHAR2(128 BYTE),
	"PRODUCTVERSION" VARCHAR2(255 BYTE),
	"DBSCHEMA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARTIFACTEXECUTIONATTR
--------------------------------------------------------

  CREATE TABLE "DBDEPLOY01"."ARTIFACTEXECUTIONATTR"
   (	"DEPLOYEXECUTIONID" NUMBER(19,0),
	"ATTRNAME" VARCHAR2(128 BYTE),
	"ATTRVALUE" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TABLE_A
--------------------------------------------------------

  CREATE TABLE "DBDEPLOY01"."TABLE_A"
   (	"A_ID" NUMBER(*,0),
	"B_ID" NUMBER(*,0),
	"STRING_FIELD" VARCHAR2(30 BYTE),
	"TIMESTAMP_FIELD" TIMESTAMP (6),
	"C_ID" NUMBER(*,0),
	"EXTRA1" NUMBER(*,0),
	"EXTRA2" NUMBER(*,0),
	"EXTRA3" NUMBER(*,0),
	"EXTRA4" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TABLE_B
--------------------------------------------------------

  CREATE TABLE "DBDEPLOY01"."TABLE_B"
   (	"B_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence MYSEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "DBDEPLOY01"."MYSEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence MYSEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "DBDEPLOY01"."MYSEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Index DEPL_EXEC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBDEPLOY01"."DEPL_EXEC_PK" ON "DBDEPLOY01"."ARTIFACTEXECUTION" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARTDEFPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBDEPLOY01"."ARTDEFPK" ON "DBDEPLOY01"."ARTIFACTDEPLOYMENT" ("ARTIFACTPATH", "OBJECTNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Function FUNC_WITH_OVERLOAD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "DBDEPLOY01"."FUNC_WITH_OVERLOAD" (IN input INT, IN invalstr VARCHAR(32), OUT mycount INT) RETURNS INT AS $$
BEGIN
    SELECT count(*) into mycount FROM TABLE_A;
END;
$$ LANGUAGE plpgsql;

/
--------------------------------------------------------
--  DDL for Function SP3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "DBDEPLOY01"."SP3" (OUT mycount INT) RETURNS INT AS $$
BEGIN
    SELECT count(*) into mycount FROM TABLE_A;
END;
$$ LANGUAGE plpgsql;

/
--------------------------------------------------------
--  Constraints for Table TABLE_A
--------------------------------------------------------

  ALTER TABLE "DBDEPLOY01"."TABLE_A" ADD PRIMARY KEY ("A_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBDEPLOY01"."TABLE_A" MODIFY ("B_ID" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."TABLE_A" MODIFY ("A_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLE_B
--------------------------------------------------------

  ALTER TABLE "DBDEPLOY01"."TABLE_B" ADD PRIMARY KEY ("B_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBDEPLOY01"."TABLE_B" MODIFY ("B_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTIFACTEXECUTIONATTR
--------------------------------------------------------

  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTIONATTR" MODIFY ("ATTRVALUE" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTIONATTR" MODIFY ("ATTRNAME" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTIONATTR" MODIFY ("DEPLOYEXECUTIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTIFACTDEPLOYMENT
--------------------------------------------------------

  ALTER TABLE "DBDEPLOY01"."ARTIFACTDEPLOYMENT" ADD CONSTRAINT "ARTDEFPK" PRIMARY KEY ("ARTIFACTPATH", "OBJECTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBDEPLOY01"."ARTIFACTDEPLOYMENT" MODIFY ("OBJECTNAME" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTDEPLOYMENT" MODIFY ("ARTIFACTPATH" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTDEPLOYMENT" MODIFY ("ARTFTYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTIFACTEXECUTION
--------------------------------------------------------

  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" ADD CONSTRAINT "DEPL_EXEC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" MODIFY ("ROLLBACK_COMMAND" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" MODIFY ("INIT_COMMAND" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" MODIFY ("TOOLVERSION" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" MODIFY ("EXECUTORID" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" MODIFY ("DEPLOYTIME" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TABLE_A
--------------------------------------------------------

  ALTER TABLE "DBDEPLOY01"."TABLE_A" ADD FOREIGN KEY ("B_ID")
	  REFERENCES "DBDEPLOY01"."TABLE_B" ("B_ID") ENABLE;
