//// CHANGE name="create"
-- This object is to test out the various ways Oracle can create
CREATE TABLE TABLE_INDEX_TEST (
	MYID    INT	NOT NULL,
	ID1    INT	NOT NULL,
	ID2    INT	NOT NULL,
	ID3    INT	NOT NULL,
	LOB_FIELD CLOB,
	STRING_FIELD	VARCHAR(30)	NULL,
	TIMESTAMP_FIELD	TIMESTAMP	NULL
) LOB (LOB_FIELD) STORE AS BASICFILE TI_LOB_FIELD (CHUNK 4096)
GO

//// CHANGE name="TABLE_INDEX_TEST_PK"
-- define the PK separately from the CREATE TABLE to help test reverse engineering
-- (ensuring that the reverse-engineering works whether or not the PK is defined separately)
ALTER TABLE TABLE_INDEX_TEST ADD CONSTRAINT TABLE_INDEX_TEST_PK PRIMARY KEY (MYID)
GO

//// CHANGE name="TABLE_INDEX_TEST_UNQ1"
-- verifying UNIQUE CONSTRAINT index creation
ALTER TABLE TABLE_INDEX_TEST ADD CONSTRAINT TABLE_INDEX_TEST_UNQ1 UNIQUE (ID1, ID2)
GO

//// CHANGE name="TABLE_INDEX_TEST_UNQ2_IND"
-- verifying UNIQUE CONSTRAINT index creation when the index was created separately
CREATE INDEX TABLE_INDEX_TEST_UNQ2_IND ON TABLE_INDEX_TEST (ID2, ID3)
GO

//// CHANGE name="TABLE_INDEX_TEST_UNQ2"
ALTER TABLE TABLE_INDEX_TEST ADD CONSTRAINT TABLE_INDEX_TEST_UNQ2 UNIQUE (ID2, ID3)
GO
