//// CHANGE name=chng1
CREATE TABLE TABLE_B (
	B_ID    INT	NOT NULL,
	VAL1    INT,
	VAL2    INT,
	VAL3    INT,
    PRIMARY KEY (B_ID)
)

//// CHANGE INDEX name=TABLE_B_IND1
CREATE INDEX TABLE_B_IND1 ON TABLE_B ( VAL1, VAL2)
