//// CHANGE name=chng1
CREATE TABLE TABLE_C (
    C_ID INT NOT NULL,
    PRIMARY KEY (C_ID)
)
GO

//// CHANGE DROP_DEPENDENT_FKS

//// CHANGE DROP_TABLE

//// CHANGE name=recreate
CREATE TABLE TABLE_C (
    C_ID INT NOT NULL,
    PRIMARY KEY (C_ID)
)
GO
