//// CHANGE name=chng1
CREATE TABLE TABLE_B (
	B_ID    INT	NOT NULL,
    PRIMARY KEY (B_ID)
)

//// CHANGE name=chng2
ALTER TABLE TABLE_B ADD COLUMN COLABC INT NULL
GO


//// CHANGE name=ind1 changeset=phaseA
CREATE INDEX TABLE_B_IND1 ON TABLE_B(B_ID)
GO
