CREATE TABLE TABLE_A (
	A_ID    INT	NOT NULL,
	COL2 INT NULL,
	COL3 INT NULL
)
GO
ALTER TABLE TABLE_A ADD PRIMARY KEY (A_ID)
GO
ALTER TABLE TABLE_A ADD FOREIGN KEY FK_B (B_ID) REFERENCES TABLE_B(B_ID)
GO
CREATE INDEX TABLE_A_IND ON TABLE_A(COL2, COL3)
GO
ALTER TABLE TABLE_A ADD COLUMN COL10 INT NULL
GO



