/****** Object:  Table [dbo].[ARTIFACTEXECUTION]    Script Date: 1/1/2017 12:00:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTIFACTEXECUTION](
	[ID] [bigint] NOT NULL,
	[STATUS] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DEPLOYTIME] [datetime] NOT NULL,
	[EXECUTORID] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TOOLVERSION] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[INIT_COMMAND] [int] NOT NULL,
	[ROLLBACK_COMMAND] [int] NOT NULL,
	[REQUESTERID] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRODUCTVERSION] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DBSCHEMA] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [DEPL_EXEC_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
