/****** Object:  Table [dbo].[ARTIFACTEXECUTIONATTR]    Script Date: 1/1/2017 12:00:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTIFACTEXECUTIONATTR](
	[DEPLOYEXECUTIONID] [bigint] NOT NULL,
	[ATTRNAME] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ATTRVALUE] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]

GO
