/****** Object:  Table [dbo].[ARTIFACTDEPLOYMENT]    Script Date: 1/1/2017 12:00:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTIFACTDEPLOYMENT](
	[ARTFTYPE] [varchar](31) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ARTIFACTPATH] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OBJECTNAME] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ACTIVE] [int] NULL,
	[CHANGETYPE] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTENTHASH] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DBSCHEMA] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPLOY_USER_ID] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TIME_INSERTED] [datetime] NULL,
	[TIME_UPDATED] [datetime] NULL,
	[ROLLBACKCONTENT] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSERTDEPLOYID] [bigint] NULL,
	[UPDATEDEPLOYID] [bigint] NULL,
 CONSTRAINT [ARTDEFPK] PRIMARY KEY CLUSTERED 
(
	[ARTIFACTPATH] ASC,
	[OBJECTNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
