CREATE OR REPLACE EDITIONABLE TRIGGER TRIGGER1
AFTER LOGON
ON DBDEPLOY01.schema
--ON database
DECLARE
BEGIN
EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA=DBDEPLOY01';
END
/
ALTER TRIGGER TRIGGER1 ENABLE
GO