//// CHANGE name=init
CREATE TABLE ATTRIBUTE_METADATA  ( 
	ATTRIBUTE_ID      	bigint NOT NULL,
	ATTRIBUTE_GROUP   	varchar(25) NULL,
	ATTRIBUTE_CATEGORY	varchar(25) NULL,
	ATTRIBUTE_NAME    	varchar(25) NULL,
	ATTRIBUTE_TYPE    	varchar(25) NULL,
	IN_TMSTMP         	timestamp NULL,
	OUT_TMSTMP        	timestamp NULL,
	EFF_TMSTMP        	timestamp NULL,
	EXP_TMSTMP        	timestamp NULL,
	PRIMARY KEY(ATTRIBUTE_ID)
)
GO

CREATE TABLE ATTRIBUTE_METADATA_WRK  (
	ATTRIBUTE_ID      	bigint NOT NULL,
	ATTRIBUTE_GROUP   	varchar(25) NULL,
	ATTRIBUTE_CATEGORY	varchar(25) NULL,
	ATTRIBUTE_NAME    	varchar(25) NULL,
	ATTRIBUTE_TYPE    	varchar(25) NULL,
	IN_TMSTMP         	timestamp NULL,
	OUT_TMSTMP        	timestamp NULL,
	EFF_TMSTMP        	timestamp NULL,
	EXP_TMSTMP        	timestamp NULL,
	PRIMARY KEY(ATTRIBUTE_ID)
)
GO

//// CHANGE INDEX name=index_ATTRIBUTE_METADATA_ATTRIBUTE_CATEGORY
CREATE UNIque LF INDEX ATTRIBUTE_METADATA_ATTRIBUTE_CATEGORY
	ON ATTRIBUTE_METADATA(ATTRIBUTE_CATEGORY)
GO

CREATE UNIQUE LF INDEX ATTRIBUTE_METADATA_WRK_ATTRIBUTE_CATEGORY
	ON ATTRIBUTE_METADATA_WRK(ATTRIBUTE_CATEGORY)
GO

//// CHANGE INDEX name=index_ATTRIBUTE_METADATA_OUT_TMSTMP
CREATE LF INDEX ATTRIBUTE_METADATA_OUT_TMSTMP
	ON ATTRIBUTE_METADATA(OUT_TMSTMP)
GO

CREATE LF INDEX ATTRIBUTE_METADATA_WRK_OUT_TMSTMP
	ON ATTRIBUTE_METADATA_WRK(OUT_TMSTMP)
GO
