//// CHANGE name=change0
CREATE TABLE NESTED_TABLE 
   (	ID NUMBER, 
	COL1 NESTED_TABLE_TYPE 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS 
 NESTED TABLE COL1 STORE AS COL1_TAB
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE USERS ) RETURN AS VALUE
GO
