//// CHANGE name=change0
CREATE TABLE TABLE_B 
   (	B_ID NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY (B_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS
GO
