//// CHANGE name=change0
CREATE TABLE TABLE_INDEX_TEST 
   (	MYID NUMBER(*,0) NOT NULL ENABLE, 
	ID1 NUMBER(*,0) NOT NULL ENABLE, 
	ID2 NUMBER(*,0) NOT NULL ENABLE, 
	ID3 NUMBER(*,0) NOT NULL ENABLE, 
	LOB_FIELD CLOB, 
	STRING_FIELD VARCHAR2(30), 
	TIMESTAMP_FIELD TIMESTAMP (6), 
	 CONSTRAINT TABLE_INDEX_TEST_PK PRIMARY KEY (MYID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE, 
	 CONSTRAINT TABLE_INDEX_TEST_UNQ1 UNIQUE (ID1, ID2)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE, 
	 CONSTRAINT TABLE_INDEX_TEST_UNQ2 UNIQUE (ID2, ID3)
  USING INDEX (CREATE INDEX DBDEPLOY01.TABLE_INDEX_TEST_UNQ2_IND ON TABLE_INDEX_TEST (ID2, ID3) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS )  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS 
 LOB (LOB_FIELD) STORE AS BASICFILE TI_LOB_FIELD(
  TABLESPACE USERS ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING )
GO
