//// CHANGE name=change0
CREATE TABLE TABLE_A 
   (	A_ID NUMBER(*,0) NOT NULL ENABLE, 
	B_ID NUMBER(*,0) NOT NULL ENABLE, 
	STRING_FIELD VARCHAR2(30), 
	TIMESTAMP_FIELD TIMESTAMP (6), 
	C_ID NUMBER(*,0), 
	EXTRA1 NUMBER(*,0), 
	EXTRA2 NUMBER(*,0), 
	EXTRA3 NUMBER(*,0), 
	EXTRA4 NUMBER(*,0), 
	 PRIMARY KEY (A_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE USERS  ENABLE, 
	 FOREIGN KEY (B_ID)
	  REFERENCES TABLE_B (B_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS
GO
