//// CHANGE name=change0
CREATE TABLE TABLE_B 
   (	B_ID NUMBER(*,0) NOT NULL ENABLE, 
	VAL1 NUMBER(*,0),
	VAL2 NUMBER(*,0),
	VAL3 NUMBER(*,0),
	 PRIMARY KEY (B_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS
GO

//// CHANGE INDEX name=TABLE_B_IND1
CREATE INDEX TABLE_B_IND1 ON TABLE_B (VAL1, VAL2)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE USERS
GO
