//// CHANGE name=change0
CREATE TABLE TABLE_A (
  A_ID int(11) NOT NULL,
  B_ID int(11) NOT NULL,
  STRING_FIELD varchar(30) DEFAULT NULL,
  TIMESTAMP_FIELD timestamp(6) NULL DEFAULT NULL,
  C_ID int(11) DEFAULT NULL,
  EXTRA1 int(11) DEFAULT NULL,
  EXTRA2 int(11) DEFAULT NULL,
  EXTRA3 int(11) DEFAULT NULL,
  EXTRA4 int(11) DEFAULT NULL,
  PRIMARY KEY (A_ID),
  KEY B_ID (B_ID),
  CONSTRAINT TABLE_A_ibfk_1 FOREIGN KEY (B_ID) REFERENCES TABLE_B (B_ID)
)
GO
