//// CHANGE name=change0
CREATE TABLE METADATA_TEST_TABLE 
   (	AFIELD NUMBER(*,0), 
	BFIELD NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS 
GO
