//// CHANGE name=change0
CREATE TABLE TABLE_B_WITH_MULTICOL_FK 
   (	B_ID NUMBER(*,0) NOT NULL ENABLE, 
	OTHER_A1_ID NUMBER(*,0), 
	OTHER_A2_ID NUMBER(*,0), 
	 PRIMARY KEY (B_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE USERS  ENABLE, 
	 CONSTRAINT FK_A_MULTICOL FOREIGN KEY (OTHER_A1_ID, OTHER_A2_ID)
	  REFERENCES TABLE_A_MULTICOL_PK (A1_ID, A2_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS 
GO

//// CHANGE excludeEnvs="%" comment="this_is_potentially_a_redundant_primaryKey_index_please_double_check" name=SYS_C005392
CREATE UNIQUE INDEX SYS_C005392 ON TABLE_B_WITH_MULTICOL_FK (B_ID)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE USERS
GO
