//// CHANGE name=change0
CREATE TABLE TABLE_B 
   (	B_ID NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY (B_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE USERS 
GO

//// CHANGE excludeEnvs="%" comment="this_is_potentially_a_redundant_primaryKey_index_please_double_check" name=SYS_C005606
CREATE UNIQUE INDEX SYS_C005606 ON TABLE_B (B_ID) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE USERS 
GO
