//// METADATA permissionScheme=TABLE_RO

//// CHANGE name=chng1
CREATE TABLE TABLE_A (
	A_ID    INT	NOT NULL,
	B_ID    INT	NOT NULL,
	STRING_FIELD	VARCHAR(30)	NULL,
	TIMESTAMP_FIELD	TIMESTAMP	NULL,
	DEFAULT_FIELD TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
    CONSTRAINT PK PRIMARY KEY (A_ID)
) IN ${defaultTablespace}
GO
//// CHANGE FK name=chng2
ALTER TABLE TABLE_A ADD FOREIGN KEY FK_B (B_ID) REFERENCES TABLE_B(B_ID)
GO
//// CHANGE name=chng3
ALTER TABLE TABLE_A ADD COLUMN C_ID INT NULL
GO
CREATE INDEX TABLE_A_IND1 ON TABLE_A(C_ID)
GO
//// CHANGE name=extra1
ALTER TABLE TABLE_A ADD COLUMN EXTRA1 INT NULL
GO
//// CHANGE name=extra2
ALTER TABLE TABLE_A ADD COLUMN EXTRA2 INT NULL
GO
//// CHANGE name=extra3
ALTER TABLE TABLE_A ADD COLUMN EXTRA3 INT NULL
GO
