CREATE OR REPLACE FORCE EDITIONABLE VIEW VIEW2 ("A_ID", "B_ID", "STRING_FIELD", "TIMESTAMP_FIELD", "C_ID", "EXTRA1", "EXTRA2", "EXTRA3", "EXTRA4") AS 
  SELECT "A_ID","B_ID","STRING_FIELD","TIMESTAMP_FIELD","C_ID","EXTRA1","EXTRA2","EXTRA3","EXTRA4" FROM TABLE_A WHERE A_ID = 4
GO