CREATE TABLE MY2TAB (
	EXPLAIN_REQUESTER	VARCHAR(128) NOT NULL,
	EXPLAIN_TIME     	TIMESTAMP NOT NULL,
	SOURCE_NAME      	VARCHAR(128) NOT NULL,
	SOURCE_SCHEMA    	VARCHAR(128) NOT NULL,
	SOURCE_VERSION   	VARCHAR(64) NOT NULL,
	EXPLAIN_LEVEL    	CHARACTER(1) NOT NULL,
	STMTNO           	INTEGER NOT NULL,
	SECTNO           	INTEGER NOT NULL,
	STREAM_ID        	INTEGER NOT NULL,
	SOURCE_TYPE      	CHARACTER(1) NOT NULL,
	SOURCE_ID        	INTEGER NOT NULL,
	TARGET_TYPE      	CHARACTER(1) NOT NULL,
	TARGET_ID        	INTEGER NOT NULL,
	OBJECT_SCHEMA    	VARCHAR(128),
	OBJECT_NAME      	VARCHAR(128),
	STREAM_COUNT     	DOUBLE NOT NULL,
	COLUMN_COUNT     	SMALLINT NOT NULL,
	PREDICATE_ID     	INTEGER NOT NULL,
	COLUMN_NAMES     	CLOB(2097152) LOGGED NOT COMPACT,
	PMID             	SMALLINT NOT NULL,
	SINGLE_NODE      	CHARACTER(5),
	PARTITION_COLUMNS	CLOB(2097152) LOGGED NOT COMPACT,
	SEQUENCE_SIZES   	CLOB(2097152) LOGGED NOT COMPACT 
	)
GO

ALTER TABLE MY2TAB
	ADD CONSTRAINT SQL110615095635750
	FOREIGN KEY(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
	REFERENCES EXPLAIN_STATEMENT(EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO, SECTNO)
	ON DELETE CASCADE 
	ON UPDATE NO ACTION 
GO

GRANT CONTROL ON MY2TAB TO USER DACT_DBO
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, INDEX, REFERENCES ON MY2TAB TO USER DACT_DBO WITH GRANT OPTION
GO
