
  CREATE TABLE "DBDEPLOY01"."ARTIFACTDEPLOYMENT" 
   (	"ARTFTYPE" VARCHAR2(31) NOT NULL ENABLE, 
	"ARTIFACTPATH" VARCHAR2(255) NOT NULL ENABLE, 
	"OBJECTNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(*,0), 
	"CHANGETYPE" VARCHAR2(255), 
	"CONTENTHASH" VARCHAR2(255), 
	"DBSCHEMA" VARCHAR2(255), 
	"DEPLOY_USER_ID" VARCHAR2(32), 
	"TIME_INSERTED" TIMESTAMP (6), 
	"TIME_UPDATED" TIMESTAMP (6), 
	"ROLLBACKCONTENT" VARCHAR2(2048), 
	"INSERTDEPLOYID" NUMBER(19,0), 
	"UPDATEDEPLOYID" NUMBER(19,0), 
	 CONSTRAINT "ARTDEFPK" PRIMARY KEY ("ARTIFACTPATH", "OBJECTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
~

  CREATE TABLE "DBDEPLOY01"."ARTIFACTEXECUTION" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STATUS" CHAR(1) NOT NULL ENABLE, 
	"DEPLOYTIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"EXECUTORID" VARCHAR2(128) NOT NULL ENABLE, 
	"TOOLVERSION" VARCHAR2(32) NOT NULL ENABLE, 
	"INIT_COMMAND" NUMBER(*,0) NOT NULL ENABLE, 
	"ROLLBACK_COMMAND" NUMBER(*,0) NOT NULL ENABLE, 
	"REQUESTERID" VARCHAR2(128), 
	"REASON" VARCHAR2(128), 
	"PRODUCTVERSION" VARCHAR2(255), 
	"DBSCHEMA" VARCHAR2(255), 
	 CONSTRAINT "DEPL_EXEC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
~

  CREATE TABLE "DBDEPLOY01"."ARTIFACTEXECUTIONATTR" 
   (	"DEPLOYEXECUTIONID" NUMBER(19,0) NOT NULL ENABLE, 
	"ATTRNAME" VARCHAR2(128) NOT NULL ENABLE, 
	"ATTRVALUE" VARCHAR2(128) NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
~

  CREATE TABLE "DBDEPLOY01"."COMMENT_TABLE" 
   (	"ID" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
~

  CREATE TABLE "DBDEPLOY01"."NESTED_TABLE" 
   (	"ID" NUMBER, 
	"COL1" "DBDEPLOY01"."NESTED_TABLE_TYPE" 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 NESTED TABLE "COL1" STORE AS "COL1_TAB"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE "USERS" ) RETURN AS VALUE
~

  CREATE TABLE "DBDEPLOY01"."TABLE_A" 
   (	"A_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"B_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STRING_FIELD" VARCHAR2(30), 
	"TIMESTAMP_FIELD" TIMESTAMP (6), 
	"C_ID" NUMBER(*,0), 
	"EXTRA1" NUMBER(*,0), 
	"EXTRA2" NUMBER(*,0), 
	"EXTRA3" NUMBER(*,0), 
	"EXTRA4" NUMBER(*,0), 
	 PRIMARY KEY ("A_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("B_ID")
	  REFERENCES "DBDEPLOY01"."TABLE_B" ("B_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
~

  CREATE TABLE "DBDEPLOY01"."TABLE_B" 
   (	"B_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("B_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
~

   COMMENT ON TABLE "DBDEPLOY01"."COMMENT_TABLE"  IS 'comment1'
~

   COMMENT ON COLUMN "DBDEPLOY01"."COMMENT_TABLE"."ID" IS 'comment2'
~

  CREATE UNIQUE INDEX "DBDEPLOY01"."ARTDEFPK" ON "DBDEPLOY01"."ARTIFACTDEPLOYMENT" ("ARTIFACTPATH", "OBJECTNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"
~

  CREATE UNIQUE INDEX "DBDEPLOY01"."DEPL_EXEC_PK" ON "DBDEPLOY01"."ARTIFACTEXECUTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"
~

  CREATE OR REPLACE EDITIONABLE FUNCTION "DBDEPLOY01"."FUNC_WITH_OVERLOAD" (IN input INT, IN invalstr VARCHAR(32), OUT mycount INT) RETURNS INT AS $$
BEGIN
    SELECT count(*) into mycount FROM TABLE_A;
END;
$$ LANGUAGE plpgsql;
~

   CREATE SEQUENCE  "DBDEPLOY01"."MYSEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
~

   CREATE SEQUENCE  "DBDEPLOY01"."MYSEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
~

  CREATE OR REPLACE EDITIONABLE TYPE "DBDEPLOY01"."NESTED_TABLE_TYPE" AS TABLE OF VARCHAR2(30);
~

  CREATE OR REPLACE EDITIONABLE PACKAGE "DBDEPLOY01"."PKG_ADDING_BODY" 
AS
    FUNCTION ADDING_BODY return integer;
END;

CREATE OR REPLACE EDITIONABLE PACKAGE BODY "DBDEPLOY01"."PKG_ADDING_BODY" 
AS
    FUNCTION PKG_ADDING_BODY
    RETURN integer IS
    BEGIN
        RETURN 1;
    END;
END;
~

  CREATE OR REPLACE EDITIONABLE PACKAGE "DBDEPLOY01"."PKG_FUNC_WITH_OVERLOAD" 
AS
    -- change to trigger a deployment
    FUNCTION INNER_FUNC_WITH_OVERLOAD return integer;
    FUNCTION INNER_FUNC_WITH_OVERLOAD(var1 IN integer) return integer;
    FUNCTION INNER_FUNC_WITH_OVERLOAD(var1 IN integer, INVALSTR IN VARCHAR) return integer;
END

CREATE OR REPLACE EDITIONABLE PACKAGE BODY "DBDEPLOY01"."PKG_FUNC_WITH_OVERLOAD" 
AS
    FUNCTION INNER_FUNC_WITH_OVERLOAD
    RETURN integer IS
    BEGIN
        RETURN 1;
    END;

    FUNCTION INNER_FUNC_WITH_OVERLOAD (var1 IN integer)
    RETURN integer IS
    BEGIN
        RETURN 1;
    END;

    FUNCTION INNER_FUNC_WITH_OVERLOAD (var1 IN integer, INVALSTR IN VARCHAR)
    RETURN integer IS
    BEGIN
        RETURN 1;
    END;
END
~

  CREATE OR REPLACE EDITIONABLE PACKAGE "DBDEPLOY01"."PKG_REMOVING_BODY" 
AS
    FUNCTION REMOVING_BODY return integer;
END;
~

  CREATE OR REPLACE EDITIONABLE PACKAGE "DBDEPLOY01"."PKG_SP_WITH_OVERLOAD" 
AS
    PROCEDURE SP_WITH_OVERLOAD;
    PROCEDURE SP_WITH_OVERLOAD(INVAL IN integer);
    PROCEDURE SP_WITH_OVERLOAD(var1 IN integer, INVALSTR IN VARCHAR);
END;

CREATE OR REPLACE EDITIONABLE PACKAGE BODY "DBDEPLOY01"."PKG_SP_WITH_OVERLOAD" 
AS
    PROCEDURE SP_WITH_OVERLOAD IS
    BEGIN
        DELETE FROM TABLE_A;
    END;

    PROCEDURE SP_WITH_OVERLOAD (INVAL IN integer) IS
    BEGIN
        DELETE FROM TABLE_A;
    END;

    PROCEDURE SP_WITH_OVERLOAD (var1 IN integer, INVALSTR IN VARCHAR) IS
    BEGIN
        DELETE FROM TABLE_A;
    END;
    -- change to trigger a deployment
END;
~

  CREATE OR REPLACE EDITIONABLE FUNCTION "DBDEPLOY01"."SP3" (OUT mycount INT) RETURNS INT AS $$
BEGIN
    SELECT count(*) into mycount FROM TABLE_A;
END;
$$ LANGUAGE plpgsql;
~

  CREATE OR REPLACE EDITIONABLE PROCEDURE "DBDEPLOY01"."SP_CHAR_TEST" AS
BEGIN
dbms_output.put_line('Hello world'); --目标表名
END character_test;
~

  CREATE OR REPLACE EDITIONABLE SYNONYM "DBDEPLOY01"."SYN1" FOR "DBDEPLOY01"."TABLE_A"
~

  CREATE OR REPLACE EDITIONABLE SYNONYM "DBDEPLOY01"."SYN_TO_ADD" FOR "DBDEPLOY01"."TABLE_A"
~

  CREATE OR REPLACE EDITIONABLE SYNONYM "DBDEPLOY01"."SYN_TO_UPDATE" FOR "DBDEPLOY01"."TABLE_B"
~

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DBDEPLOY01"."VIEW1" ("A_ID", "B_ID", "STRING_FIELD", "TIMESTAMP_FIELD", "C_ID", "EXTRA1", "EXTRA2", "EXTRA3", "EXTRA4") AS 
  SELECT "A_ID","B_ID","STRING_FIELD","TIMESTAMP_FIELD","C_ID","EXTRA1","EXTRA2","EXTRA3","EXTRA4" FROM VIEW2
~

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DBDEPLOY01"."VIEW2" ("A_ID", "B_ID", "STRING_FIELD", "TIMESTAMP_FIELD", "C_ID", "EXTRA1", "EXTRA2", "EXTRA3", "EXTRA4") AS 
  SELECT "A_ID","B_ID","STRING_FIELD","TIMESTAMP_FIELD","C_ID","EXTRA1","EXTRA2","EXTRA3","EXTRA4" FROM TABLE_A WHERE A_ID = 4
~
