//// METADATA permissionScheme=TABLE_RW

//// CHANGE name=chng1
CREATE TABLE TABLE_B (
	B_ID    INT	NOT NULL,
	B_FIELD INT NULL,
    CONSTRAINT PK PRIMARY KEY (B_ID)
) IN ${defaultTablespace}
GO
CREATE INDEX TABLE_B_IND1 ON TABLE_B(B_FIELD)
GO
-- testing out the add/drop of constraints for in-memory stuff
ALTER TABLE TABLE_B DROP CONSTRAINT PK
GO
ALTER TABLE TABLE_B ADD CONSTRAINT PK PRIMARY KEY (B_ID)
GO
