//// CHANGE name=change0
CREATE TABLE TABLE_A  (
		  A_ID INTEGER NOT NULL , 
		  B_ID INTEGER NOT NULL , 
		  STRING_FIELD VARCHAR(30) , 
		  TIMESTAMP_FIELD TIMESTAMP , 
		  DEFAULT_FIELD TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , 
		  C_ID INTEGER , 
		  EXTRA2 INTEGER , 
		  EXTRA3 INTEGER , 
		  MYNEWCOL INTEGER )   
		 IN "${MYTBSPACE_TSP001_token}" 
GO

//// CHANGE name=PK
ALTER TABLE TABLE_A 
	ADD CONSTRAINT PK PRIMARY KEY
		(A_ID)
GO

//// CHANGE INDEX name=TABLE_A_IND1
CREATE INDEX TABLE_A_IND1 ON TABLE_A 
		(C_ID ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS
GO

//// CHANGE FK name=FK_B
ALTER TABLE TABLE_A 
	ADD CONSTRAINT FK_B FOREIGN KEY
		(B_ID)
	REFERENCES TABLE_B
		(B_ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION
GO
