//// CHANGE name=change0
CREATE TABLE TABLE_B  (
		  B_ID INTEGER NOT NULL , 
		  B_FIELD INTEGER )   
		 IN "${MYTBSPACE_TSP001_token}" 
GO

//// CHANGE name=PK
ALTER TABLE TABLE_B 
	ADD CONSTRAINT PK PRIMARY KEY
		(B_ID)
GO

//// CHANGE INDEX name=TABLE_B_IND1
CREATE INDEX TABLE_B_IND1 ON TABLE_B 
		(B_FIELD ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS
GO
