CREATE TABLE TABLE_A (
	A_ID    INT	NOT NULL,
	B_ID    INT	NOT NULL,
	STRING_FIELD	VARCHAR(30)	NULL,
	TIMESTAMP_FIELD	TIMESTAMP	NULL,
	C_ID    INT	NULL,
	EXTRA1    INT	NULL,
	EXTRA2    INT	NULL,
	EXTRA3    INT	NULL,
    PRIMARY KEY (A_ID)
)
GO
ALTER TABLE TABLE_A ADD FOREIGN KEY (B_ID) REFERENCES TABLE_B(B_ID)
GO
