//// CHANGE name=chng1
CREATE TABLE TABLE_A (
	A_ID    INT	NOT NULL,
	B_ID    INT	NOT NULL,
	STRING_FIELD	VARCHAR(30)	NULL,
	STRING_FIELD_DEFAULT	VARCHAR(30)	NULL DEFAULT '合',
    TIMESTAMP_FIELD	TIMESTAMP	NULL,
	DEFAULT_FIELD TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
)
GO
CREATE UNIQUE INDEX TABLE_A_PK ON TABLE_A (A_ID)
GO

//// CHANGE FK name=chng2
ALTER TABLE TABLE_A ADD FOREIGN KEY (B_ID) REFERENCES TABLE_B(B_ID)
GO
//// CHANGE name=chng3
ALTER TABLE TABLE_A ADD COLUMN C_ID INT NULL
GO
//// CHANGE name=extra1
ALTER TABLE TABLE_A ADD COLUMN EXTRA1 INT NULL
GO
//// CHANGE name=extra2
ALTER TABLE TABLE_A ADD COLUMN EXTRA2 INT NULL
GO
//// CHANGE name=extra3
ALTER TABLE TABLE_A ADD COLUMN EXTRA3 INT NULL
GO
