//// CHANGE name="create"
CREATE TABLE TABLE_SPECIAL_COL (
	MYID    INT	NOT NULL,
	LOB_FIELD CLOB,
	XML_FIELD XMLTYPE,
	STRING_FIELD	VARCHAR(30)	NULL,
	TIMESTAMP_FIELD	TIMESTAMP	NULL,
	PRIMARY KEY (MYID)
) LOB (LOB_FIELD) STORE AS BASICFILE TSC_LOB_FIELD (CHUNK 4096)
GO
