CREATE OR REPLACE PACKAGE PKG_ADDING_BODY
AS
    FUNCTION ADDING_BODY return integer;
END;

GO

//// BODY
CREATE OR REPLACE PACKAGE BODY PKG_ADDING_BODY
AS
    FUNCTION PKG_ADDING_BODY
    RETURN integer IS
    BEGIN
        RETURN 1;
    END;
END;
GO
