CREATE TABLE ARTIFACTDEPLOYMENT ( 
	ARTFTYPE       	varchar(31) NOT NULL,
	ARTIFACTPATH   	varchar(255) NOT NULL,
	OBJECTNAME     	varchar(255) NOT NULL,
	ACTIVE         	int NULL,
	CHANGETYPE     	varchar(255) NULL,
	CONTENTHASH    	varchar(255) NULL default "20140101",
	DBSCHEMA       	varchar(255) NULL,
	DEPLOY_USER_ID 	varchar(32) NULL,
	TIME_UPDATED   	datetime NULL,
	ROLLBACKCONTENT	varchar(2048) NULL,
	CONSTRAINT ARTDEFPK PRIMARY KEY(ARTIFACTPATH,OBJECTNAME)
	WITH max_rows_per_page = 0
	)
GO

